apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: voting
resources:
- namespace.yaml
- db-deployment.yaml
- db-service.yaml
- ingress.yaml
- kustomization.yaml
- redis-deployment.yaml
- redis-service.yaml
- result-deployment.yaml
- result-service.yaml
- vote-deployment.yaml
- vote-service.yaml
- worker-deployment.yaml
